scene.setBackgroundColor(11)
let buyingBooksScore = 0
game.splash("you are buying books today,", "so don't fail the librarian!!!")
game.splash("do you wan't to buy the book dinasours of the anceint?")
game.showLongText("in years long ago, people didn't exist but something else existed, it was sometimes small sometimes large it was a dinosuor those great animals were a great rular of the world but eventuly they died out that was sad but when sientists shared this with other people, they would remember the time too.", DialogLayout.Bottom)
if (game.ask("           yes", "         no")) {
    buyingBooksScore += 1
} else {
    game.splash("ok let's move on.")
}
game.splash("do you wan't to buy the book the entertainment of life?")
game.showLongText("life is something you have but think about your feelings sometimes you are borad but you don't wan't to wait for something to happen so you are not borad anymore well this is life, and life sometimes may not go the way ou wan't to, and when borad well what things do you have around can you color? do you like video games play those?!! there are many things you can do when you are borad so when you need to do something thing about the things and people around you !!#%*&^##$^^ %^%^%$$&@! !$#%$#^@ @$@.", DialogLayout.Bottom)
game.splash("ooh this looks intresting it has a secret to uncover the %#^%%#%^*& symbowls they defenitly have a secret in hand!!!")
if (game.ask("          yes", "           no")) {
    buyingBooksScore += 1
} else {
    game.splash("ok let's move on.")
    if (buyingBooksScore == 0) {
        game.splash("i don't know why your not buying books?")
    }
}
game.splash("do you wan't to buy mornings delight?")
game.showLongText("mornings are nice but this girls morning was better!! Once upon a time a little girl woke up her name was Isla she had a happy day epessally a happy morning. when she woke up thismorning she found presents at her bedside but it wasn't chrismis she new it. She asked her parents why their were presents!! her parents said a spesial suprise for my little duather those presents are for you! go open them we got it for you said her mom her mom was very nice she was quite tall thugho her age was 7 her dad was 26 he was a bit shorter than her mom. when she got back to her room she expected to hear them say oh don't forget to clean your room she lisened close, but they never said it! so she looked away to see her room but it was all cleaned for her not a speck of dust on the ground and she opened her present and it was a time traveler! you thught that was enoth reading you get the point right?", DialogLayout.Bottom)
if (game.ask("      yes buy this book", "  no i don't wan't it")) {
    buyingBooksScore += 1
} else {
    if (buyingBooksScore == 0) {
        game.splash("i still really don't know why your not buying thease books?")
    }
}
game.splash("well, another book coming up!!")
if (buyingBooksScore == 0 || buyingBooksScore == 1) {
    game.splash("i hope you like this|:")
} else {
	
}
game.splash("do you wan't to buy the lost ball?")
game.showLongText("i can't wait to go to soccer today it's the ultimate match i got to get ready get all your stuff if your going don't forget the ball got everything packed? mom said of course i do, good said her mom joey was very exited he was already going to a match i got to go said joey but then he saw that the very very important ball was missing uh oh said joey in a low scared voice he called to his mom that the ball was lost. they looked and looked but they didn't find it anywere they went they even asked their neiboors but they still didn't find it so they wen't to the soccer field to tell everyone and then jhon said ware have you been we were looking for the ball said joey ha ha did you forget i was the one looking after the ball this time? said jhon oh ha ha said joey, i guess i did forget and they played and played other times and they lived hapily ever after. THE END", DialogLayout.Bottom)
game.splash("come, on let's get this next story going!!!(:")
if (game.ask("            yes buy", "    no i won't take it")) {
    // changes how the librarian acts to you.
    buyingBooksScore += 1
} else {
    game.splash("come, on time for the next one.")
}
if (game.ask("yes", "no")) {
    // changes how the librarian acts to you.
    buyingBooksScore += 1
} else {
    game.splash("let's see what you bout.", "It's the intresting part!!")
}
game.splash("inferno volcanos!!")
game.splash("ooh this must be about volcanos!!")
game.splash("this can't be fiction")
game.showLongText("volcanos are a source of hot real hot but have you ever wondered how they erupt well the earth is made out of not just a ball of land but 4 parts the innner core the outer core the mantle and the crust we live on the crust the core is the part thats hot real hot real real real hot and when enogth presure builds up in it it can burst open the crust making werever it comes up a slide up that is the shape of a volcano. there are a lot more facts but you don't need to read all of it now do you?", DialogLayout.Bottom)
game.splash("if you read non-fiction you can learn new stuff!!", "this is non-fiction WOW!!!!")
game.splash("do you wan't to buy the inferno volcanos?")
if (buyingBooksScore > 1) {
    scene.setBackgroundImage(img`
        ..........................ee...........e.........................ffffffffffffffffffffffff.......................................................................
        ...........................e.........ee.......................fffffffffffffffffffffffffffff.....................................................................
        .............2........2....ee.......e......................ffffffffffffffdddddddfffffffffff.....................................................................
        .............2........2....ee.....ee......................ffffffffffdddddddddddddddffffffff.......................................22...........2................
        .............2........2.....e.55.ee.......................ffffffdffdddddddddddd2ddddfffffff.......................................2............2................
        .............2........2.....e555ee........................fffffdffddd2ddddddddd2dddddfffffffff....................................2............2................
        .............2........2....55555e....................fffffffffddfdddd2ddddddddd2dddddfdffffffffff..................................2...........2................
        .............2........2....555555.....d..............fffffffffddddddd2ddddddddd2ddddddddfffffffff..................................2...........2................
        .............2........2....555555...dddd............fffffffffdddddddd2ddddddddd2ddddddddfffffffff..................................2...........2................
        .............2.........2...555555.dddddd............ffffffffddddddddd2ddddddddd2dddddddddffffffff..................................2...........2................
        .............2.........2...555555dddddddd...........ffffffffddddddddd2ddddddddd2ddddddddddfffffff..................................2...........2................
        .............2..........2..5555...dddddddd..........fffffffdddddddddd2ddddddddd2dddddddddddffffff..................d...............2...........2................
        ............2...........2..5555..ddddddddd..........fffffffdddddddddd2ddddddddd2dddddddddddffffff.................d................2............2...............
        ............2...........2...55...dddddddddd.........fffffffdddddddddd2ddddddddd2dddddddddddfffff..................dd...............2............2...............
        ............2...........2........dddddddddd.....f...ffffffddddddddddd2ddddddddddddddddddddddffff..ffff...........ddd............................2...............
        ............2...........2........dddddddddd....fff.fffffffddddddddddddddddddddddddddddddddddfffffffffff.........dddd.........22.................................
        ............2...........2........dddddddddd....fffffffffffddddddddddddddddddddddddddddddddddfffffffffff.........ddddd........222......................22........
        ............2...........2........dddddddddd....fffffffffffddddddddddddddddddddddddddddddddddfffffffffff........dddddd........2.22....................22.........
        ............2...........2........dddddddddd....fffffffffffddddddddddddddddddddddddddddd2ddddffffffffff........ddddddd.........2ff2.................22.2.........
        ............2...................ddddddddddd....fffffffffffddd2ddddddddddddddddddddddddd2ddddffffffffff........dddddddd........2fff2222...........22ff2..........
        ..............................2.dddddddddddd..ffffffffffffdddd2dddddddddddddddddddddddd2ddddfffffffffffffff..ddddddddd........2fffffff22222222222ffff2..........
        .............................22.dddddddddddd..ffffffffffffdddd2ddddddddddddddddddddddd22ddddfffffffffffffff.dddddddddd........22ffffffffffffffffffff2...........
        .....222....................2f2.dddddddddddd..fffffffffffffdddd2dddddddddddddddddddddd2dddddffffffffffffff..ddddddddddd.........22fffff3333333fffff2............
        ....22f2...................22f2.dddddddddddd..ffffffffffffffdddd2dddddddddddddddddddd22ddddddfffffffffffff.dddddddddddd...........22ff333333333fff2.............
        ....2fff22...............22fff2.dddddddddddd..ffffffffffffffffdd22dddddddddddddddddd2ddddddddfffffffffffffddddddddddddd.............22222223322222..............
        .....2fff2.............22ffff2..dddddddddddd..fffffffffffffffffddd222ddddddddddddd222dddddddfffffffffffff.dddddddddddddd...................22...................
        .....2ffff222...22222222fffff2.ddddddddddddd..fffffff888888ffffdddddd2222222222222ddddddddddfffffffffffffddddddddddddddd........................................
        ......2ffffff222ffffffffffff2..ddddddddddddd..ffffff8888888fffdddddddddddddddddddddddddddddd88888888ffffdddddddddddddddd........................................
        .......2fffffffffffffffffff2...dddddddddddddd.fffff8888888888fdddddddddddddddddddddddddddd88888888888ff.ddddddddddddddddd.......................................
        ........2ffff333333fffffff2....dddddddddddddd.fffff88888888888d8dddddddddddddddddddddddddd888888888888fdddddddddddddddddd.......................................
        .........22333333333fffff2.....dddddddddddddd.fffff888888888888888dddddddddddddddddddddddd888888888888ddddddddddddddddddd.......................................
        ...........22333333332222......ddddddddddddddffffff888888888888888888dddddddddddddddddddd8888888888888dddddddddddddddddddd......................................
        .............22333222..........ddddddddddddddf.ffff888888888888888888888dddddddddddddd.888888888888888dddddddddddddddddddd......................................
        ...............222..............ddddddddddddd...ff88888888888888888888888888888888888d888888888888888.dddddddddddddddddddd......................................
        ................................ddddddddddddd...ff88888888888888888888888888888888888888888888888888ddddddddddddddddddddddd.....................................
        ................................ddddddddddddd....ff8888888888888888888888888888888888888888888888888ddddddddddddddddddddddd.....................................
        ................................dddddddddddd......88888888888888888888888888888888888888888888888888ddddddddddddddddddddddd.....................................
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddd88888888888eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee88888888888ddddddddddddddddddddddddeeeeeeeeeeeeeeeeeee7eeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddd88888888888eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee8888888888dddddddddddddddddddddddddeeeeeeeeeeeeeeeee7777eeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddd88888888888eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee8888888888dddddddddddddddddddddddddeeeeeeeeeeeeeeee775577eeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddd8888888888eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee888888888dddddddddddddddddddddddddeeeeeeeeeeeeeee77555777eeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddd8888888eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee88888888dddddddddddddddddddddddddeeeeeeeeeeeeee7777757777eeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddd888eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee8888888dddddddddddddddddddddddddeeeeeeeeeeeee77757755777feeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddd888eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee88888dddddddddddddddddddddddddeeeeeeeeeeee71177557557f7eeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee8888dddddddddddddddddddddddddeeeeeeeeeee71111175577f757eeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee888dddddddddddddddddddddddddeeeeeeeeee71111111177f757eeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee8dddddddddddddddddddddddddeeeeeeeeee7111111111f757eeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddeeeeeeeeeee71111111f757eeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddeeeeeeeeeeee777777f777eeeeeeeeeeeeeee
        ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdddddddddddddddddddddddddfffffffffffffffffffffffffffffffffffff
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        ..............22222.............................................................................................................................................
        ............22222222..........................................................222222............................................................................
        ..........2222222222.......................................................222222222222.........................................................................
        ........2222222222222....................................................2222222222222222.......................................................................
        ......222222222222222..................................................222222222222222222.............22........................................................
        .....2222222222222222.................................................222222222222222222.............22222......................................................
        ....2222222222222222..................................................2222222222222222..............222222......................................................
        ...2222222222222222...................................................22222222222222...............2222222......................................................
        ...22222222222222.............................2222...................2222222222....................222222..2222222222................................2222222....
        ..22222222222................222222222.......222222.................222222222......................222222.22222222222..............................222222222222.
        ..222222222................2222222222222.....222222.................2222222........................222222222222222222.............................2222222222222.
        .22222222.................222222222222222....222222................2222222.........................222222222222222222.............................2222222222222.
        .2222222.................22222222222222222...222222222222..........2222222.........................22222222222222222.............................222222...2222..
        22222222.................22222222222222222...22222222222222.......2222222..........2...............2222222222..........................222.......22222..........
        2222222.................2222222222222222222..2222222222222222....2222222.....2222222222222.........22222222.........2222222............222.......222222222......
        2222222............222..2222222.......22222..2222222222222222....2222222.....2222222222222222......222222.........22222222222.........2222.......2222222222.....
        2222222...........22222.2222222.......22222..2222222222222222....22222222....22222222222222222.....222222........2222222222222........2222........22222222222...
        2222222.........2222222.2222222.......22222..222222....2222222...222222222...22222222222222222.....22222.........2222222222222.....2222222...........222222222..
        .222222........22222222.2222222.......22222..222222.....222222...222222222.....2222222222222222....22222........22222222222222222.2222222222..............2222..
        .222222........22222222.2222222.......22222..222222......22222...2222222222222.......2222222222....22222........222222.....2222222.2222222222..............2222.
        .222222.......22222222..2222222.......22222..222222......22222...222222222222222222..2222222222....22222........222222.....2222222..22222222...............2222.
        .222222222222222222222..2222222.......22222..222222.......2222...22222222222222222222222222222.....22222........222222.....22222222..22222................22222.
        .222222222222222222222..2222222222222222222..222222.......22222..22222222222222222222222222222.....22222........222222.....22222222..2222.................22222.
        ..2222222222222222222....22222222222222222...222222........2222..22222222222222222222222222222.....22222........222222.....22222222..2222....222..........2222..
        ...222222222222222222....22222222222222222...222222........2222..22222222222222222222222222222.....22222........2222222222222222222...222...222222....22222222..
        ...222222222222222222.....222222222222222....222222........2222...2222222222222222222222222222.....22222.........222222222222222222...222...22222222222222222...
        ....2222222222222222.......2222222222222.....222222........2222....2222222222222222222222222.......22222.........222222222222222222...222...2222222222222222....
        ......2222222222222..........222222222.......2.222.........2222....2..2222222222222222222222.......22222..........22222222222..2222...222.....222222222222......
        ........222222222...................................................2....222222222222222............2222............2222222....22......22..........22222........
        ....................................................................................................222.........................................................
        `)
    game.splash("congrats you helped the librarian!!!!!!!")
    pause(5000)
    game.over(true)
} else {
    scene.setBackgroundImage(img`
        ................................................................................................................................................................
        .................................................................2..............................................................2...............................
        .................................................................2................................2222........................22................................
        ..................................................................2...................................22222..................2..................................
        ..................................................................2.........................................................2...................................
        .............................2222.................................2........................................................2....................................
        .........2...........................2........22222222............2.......................................................2.........22222222222222222222222.....
        .........2..........................22.......2.......2............2......................................................2.................................222..
        ..........2.........................22......2.........2............2................2....................................2......................................
        ...........2.......................22......2..........2............2................2...........................................................................
        ............2.....................22......2...........2............2................2...........................................................................
        .............2...................22......2.............2...........2...2............2...........................................................................
        ..............2.................22......2..............2...........2...2............2...........................................................................
        ...............2................22.....2...........2....2..........2..2.............2...........................................................................
        ................2..............22......2..........2.....2..........2..2............22.................2........2...............22...............................
        .................2............22......2...........2.....2..........2..2............22.................2......................22..2..............................
        .................2............2.......2..........2......2..........2.2.............22.................2....................22....2..............................
        ..................2..........2.......2...........2......2.........2..2.............22.................2...................2......2..............................
        ...................2.........2.......2..........2.......2............2............2.2.................2..................2........2.................2...........
        ....................2.......22.......2.........2........2............2............2.2.................2..................2........2.................2...........
        .....................2......2.......2...................2...........2.............2.2.................2.................2.........2................2............
        ......................2....22.......2...................2...........2.............2.2.................2.................2.........2................2............
        .......................2...2........2...................2............2............2.2.................2.................2.........2................2............
        ........................2.2.........2...................2............2...........2..2.................2........2........2.........2................2............
        .........................22.........2...................2............2..........2...2.........2222....2.......2.........22222222222................2............
        ................2222222..2..........2...................2.............2........2....2..........2.22...2.......2.........2...........................2...........
        ..............22.........2..........2...................2.............2........2....2..........2...22.2.......2.........2...........................2...........
        ........................2...........2...................2..............2......2.....2..........2.....22......2...........2..........................2...........
        ........................2............2.................2...............2.....2......2...........2....2.......2...........2...............22222222...2...........
        .......................2.............22................2................22222.......2...........2....2.......2............2..............2......222222..........
        .......................2.............22...............2.............................2............2...2.......2.............2............2............22.........
        ......................2...............22.............2..............................2............2...2.......2..............2...........2............22.........
        ......................2...............2...........222...............................22...........2..2........2...............2..........2............2..........
        .....................2................222..2222222................................................2.2........2................22.........2...........2..........
        .....................2...................22.......................................................222........2...........................22..........2..........
        ....................2........................................................................................2.............................2........2...........
        ...................2........................................................................................................................2.......2...........
        ..................2..........................................................................................................................222..22............
        .................22.............................................................................................................................222.............
        ............2....2..............................................................................................................................................
        ...........2....................................................................................................................................................
        ...........2....................................................................................................................................................
        ..........2.....................................................................................................................................................
        ..........2............................................22................................................2......................................................
        .........2............................................2...................................................22....................................................
        .........2....................................2......2......................................................2...................................................
        ............................................22......2........................................................2..................................................
        ...........................................2......22............................2............................2..................................................
        ..........................................2......2.............................2..22222.......................2.....................2222........................
        ........................................22......2............................22222.....222.....................2........................222.....................
        .......................................2.......2.............................2............222...................2..........................222..................
        ......................................2.......2.............................2....................................2............................22................
        ....................................22.....................................2......................................2.............................22..............
        ...................................2.......................................2.......................................2.............................2..............
        ..................................2.......................................2.........................................2.............................2.............
        .................................2.......................................2...........................................2.............................2............
        ................................2.......................................2.............................................2.........................................
        ..............................22........................................2..............................................2........................................
        .............................2.........................................2................................................2.......................................
        ............................2..........................................2...2.............................................2......................................
        ..........................22...........................................2..2...............................................2.....................................
        ........................22..............................................22.................................................2....................................
        .......................2...............................................2............................22......................2...................................
        ......................2...............................................2.........................2222.....2...................2..................................
        .....................2...........2...................................2........................22........2.....................2.................................
        ...................22............2..................................2.................................22.......................2................................
        ...............2222..............2.................................2.................................2..........................2...............................
        .............22..................2.................................2................................2...........................................................
        .................................2................................2................................2............................................................
        .................................2...............................2................................2.............................................................
        .................................2...............................2................................2.............................................................
        .................................2...............................................................2...........................................2..................
        ................................2...............................................................2..........................................22...................
        ................................2...............................................................2.........................................2.....................
        ................................2...............2..............................................2........................................22......................
        ................................2...............2.....................................2........2......................................22........................
        ................................2................2.....................................2.......2.....................................2..........................
        ...............................2..................2.....................................2......2................................................................
        ...............................2..................2......................................2......2...............................................................
        ...............................2...................2.....................................2......2........................................................22.....
        ...............................2....................22...................................2.......2............2........................................22.......
        ..............................2.......................2...................................2....................2.....................................22.........
        .......................................................2..................................2.....................22.................................22...........
        .......................................22...............22.................................2......................22..............................2.............
        .....................................22...................22...............................2........................2............................2..............
        ...................................22.......................222............................2.........................22.........................2...............
        .................................22............................22...........................2..........................22.......................2...............
        ...............................22................................222........................2............................222222.................................
        .............................22.....................................2222.....................2.................................2222222..........................
        ...........................22....2222222222.......................22....2222.................2........................................222.......................
        .......................2222222222..............................222...........................2..................................................................
        ......................22....................................222...............................2.................................................................
        ....................22....................................22..................................2.................................................................
        .......................................................222.....................................2................................................................
        .....................................................22........................................2................................................................
        ...................................................22...........................................2...............................................................
        .................................................22.............................................2...............................................................
        ...............................................22...............................................2.....................................................222.......
        .............................................22..................................................2................................................2222..........
        ...........................................22....................................................2.............................................222..............
        .........................................22.......................................................2.......................................22222.................
        ........................................2.........................................................2.....................222........2222222..2...................
        ...................................................................................................2.......................22222222..........2..................
        ....................................................................................................2........................................2..................
        ....................................................................................................2.........................................2.................
        .....................................................................................................2........................................2.................
        ......................................................................................................2........................................2................
        ......................................................................................................2........................................2................
        .......................................................................................................2........................................2...............
        ........................................................................................................2.......................................2...............
        .........................................................................................................2......................................2...............
        .........................................................................................................2......................................2...............
        ..........................................................................................................2.....................................2...............
        ...............................................................................................................................................2................
        ...............................................................................................................................................2................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        `)
    game.splash("the librairian killed you for you'r mis-beahave-your.")
    game.over(false)
}
